### ISSUE TITLE
Software - Input dataset field selector.

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#105]
Currently, the input dataset dropdown shows no entries after adding a new software. After reloading, the dropdown show the datasets that belong to this task.  

- [x] make the dropdown list the non-deprecated datasets from the corresponding task immediately.
- [ ] Add a second selector to change the corresponding task

**Comment by BastianGrahm** [comment]
I was just fixing the issue, that with the creation of a new software in the UI the dataset dropdown is empty and implemented the first point with it.
For that I assumed that "non-deleted" means "the `is_deprecated` flag is false" and "non-hidden" means "the `is_confidential` flag is false". Am I correct there?

**Comment by MattiWe** [comment]
I've updated the issue for clarity. Confidential dataset must appear in this list, since all test datasets are confidential.
