### ISSUE TITLE
Local Development Setup: Host

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#109]
Goal: Develop on a completely local setup.
Previous Steps: Setup [tira-application locally](https://github.com/tira-io/tira/issues/102) and mount the [toy model](https://github.com/tira-io/tira/tree/master/tira-model/src) locally.

TODO: 
- [x] follow [wiki](https://github.com/tira-io/tira/wiki/Deploying-the-Backend) to setup local development host

~~If current [local host setup](https://github.com/tira-io/tira/wiki/Deploying-the-Backend) does not work, implement local setup as follows~~
- [x] ~~instructions how to install salt locally~~
- [x] ~~derive more generic (not betaweb specific) salt script from [the betaweb salt script](https://git.webis.de/code-generic/code-saltstack/-/blob/master/src/srv/salt/states/tira/tira-host/init.sls)~~
- [x] ~~run it~~
- [x] ~~fix this procedure in [documentation](https://github.com/tira-io/tira/wiki/Deploying-the-Backend)~~
- [ ] add default virtual machine (alpine) for dummy user to the toy model
- [x] switch from two makefile targets to one: specify tira model host path in a variable

**Comment by theelstner** [comment]
Trying to get the host running locally, by following [wiki](https://github.com/tira-io/tira/wiki/Deploying-the-Backend), it seems like I did not get it to work:

PREREQUISITES FOR LOCAL SETUP OF TIRA HOST
- I have ensured to have the tira-model (toy version) mounted at /mnt/nfs/tira (with mount --bind <tira-home>/tira-model/src /mnt/nfs/tira/)

RUNNING THE TIRA APPLICATION
- I have changed tira_root: /mnt/nfs/tira in tira-application/config/settings-dev.yml
- then run the application by using make run-dev in tira-application/

FOLLOWING THE LOCAL SETUP INSTRUCTIONS FOR THE HOST IN THE WIKI (Deploying the Backend)
- I have installed virtualbox 6.1.16 + extensionpack and docker locally
- I have run "sudo chown -R 1010:1010 build/initial-docker-tira-model" as recommended
- I have run "make build-tira-docker"
-  and then "make run-tira-docker-dev"

There was no error in running the container, but I can see the host is not up, because navigating the interface of the app to http://127.0.0.1:8080/task/sample-task/user/pan21-av-baseline shows "internal server eror" for the host and the commandline log prints:

INFO 2021-08-31 16:02:02,802 basehttp: "GET /public/tira/js/software.js HTTP/1.1" 200 10397
ERROR 2021-08-31 16:02:02,948 actions: /grpc/pan21-av-baseline/vm-info to localhost failed with <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1630418522.946520627","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5396,"referenced_errors":[{"created":"@1630418522.946518495","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
Traceback (most recent call last):
  File "/home/theresa/Desktop/TIRA/TIRA/tira/tira-application/src/tira/actions.py", line 315, in vm_info
    response_vm_info = grpc_client.vm_info(vm_id)
  File "/home/theresa/Desktop/TIRA/TIRA/tira/tira-application/src/tira/grpc_client.py", line 45, in vm_info
    response_vm_info = self.stub.vm_info(tira_host_pb2.RequestVmCommands(vmId=vm_name))
  File "/home/theresa/Desktop/TIRA/TIRA/tira/tira-application/venv/lib/python3.8/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/theresa/Desktop/TIRA/TIRA/tira/tira-application/venv/lib/python3.8/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1630418522.946520627","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5396,"referenced_errors":[{"created":"@1630418522.946518495","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
ERROR 2021-08-31 16:02:03,002 log: Internal Server Error: /grpc/pan21-av-baseline/vm_info
ERROR 2021-08-31 16:02:03,002 basehttp: "GET /grpc/pan21-av-baseline/vm_info HTTP/1.1" 500 49
ERROR 2021-08-31 16:02:03,002 basehttp: "GET /grpc/pan21-av-baseline/vm_info HTTP/1.1" 500 49

I don't know what went wrong at this point and I am open for hints! :)


![image](https://user-images.githubusercontent.com/12912413/131520473-7a451695-28b7-4626-a39c-e4babdad9866.png)
![image](https://user-images.githubusercontent.com/12912413/131520546-5b170458-ec17-43a5-81ed-a9d18d94fb7e.png)

**Comment by MattiWe** [comment]
Is the container running or stopped?
`-$ docker ps -a`
can you connect to the container?
`-$ docker exec -ti <container-name> bash'
Are all files there (/mnt/nfs/tira)? Is the python app running?
can you run the tira command while connected to the container?
can you create/start/stop vm's while connected to the container? Can you log into one of the created machines?

The application probably can't connect to a working host because I changed the API and have not had the time to also update the hosts.

**Comment by theelstner** [comment]
Thanks, Matti. I have the following answers to your questions:

Is the container running or stopped?->
The container is not running, it "exited (2)"
![image](https://user-images.githubusercontent.com/12912413/131854063-4f43e9e6-373b-466a-abca-fcfa810e6c0a.png)

can you connect to the container? -> no because it is not running

Are all files there (/mnt/nfs/tira)?  ->
 /mnt/nfs/tira has the tira-model/src folder mounted, and shows the directories data, /log, /model, /state
![image](https://user-images.githubusercontent.com/12912413/131854582-34eafa52-0e4e-4bdd-8b56-8230a2283d6a.png)

Is the python app running?->
By python app you mean the application? -> yes:
![image](https://user-images.githubusercontent.com/12912413/131854992-c9a1ec0f-4177-49bd-a68b-5dd0260c3496.png)

The following questions relate to the host-container, which is not running i guess?!
"can you run the tira command while connected to the container?
can you create/start/stop vm's while connected to the container? Can you log into one of the created machines?"

Any idea how i get the host-container running? Or continue from here?

**Comment by MattiWe** [comment]
`Is the container running or stopped?->
The container is not running, it "exited (2)"`

All of these questions are for the host container. You first want to figure out why the container is not working.

**Comment by theelstner** [comment]
Nikolay and I have gotten the container to run. It was a permissions issue, that has been fixed in the documentation.
(The mounted Tira-Model did not have tira user and group permissions)

Now, we have proceeded to the next hickup: The Ubuntu kernel 5.11 does not support virtualbox 6.1.16.
-> We are installing 6.1.27 and see if it works.

**Comment by theelstner** [comment]
The new [virtualbox version 1.27](https://www.virtualbox.org/wiki/Testbuilds) works.
The next hickup is caused by [this recent commit](https://github.com/tira-io/tira/commit/234d50d58aa81ad3085dc9c59a3cda584a568cdd), removing initial-docker-tira-model:
running make run-tira-docker-dev runs into an error:

![image](https://user-images.githubusercontent.com/12912413/133463655-66508410-c8f4-44dc-b7fa-93baefb43c56.png)

I "fixed" this locally, by commenting out the corresonding [line in the Dockerfile](https://github.com/tira-io/tira/blob/53df7e38f0038707aa23fb8e6b78c1519fbfafc7/tira-host/build/Dockerfile#L31)

The container is running after this, but I still get an error in  [step 19](https://github.com/tira-io/tira/blob/53df7e38f0038707aa23fb8e6b78c1519fbfafc7/tira-host/build/Dockerfile#L40):

![image](https://user-images.githubusercontent.com/12912413/133463813-ad6ba862-be5a-4b28-8d8a-c05d58d67ff2.png)


This is the reason, I did not commit yet, because I am not sure, just commenting out was the right fix. 
Any suggestions?

**Comment by MattiWe** [comment]
(a) When you start the container, mount (-v) the tira/tira-model from the outside to /mnt/nfs/tira inside the container. 
(b) add the necessary mkdirs and touches to the build script (meh)
(c) move the dockerfile out of the tira-host scope into the tira scope, so both tira-host and tira-model are in the context for copying. If we do this, we should move all build utility from all modules in the tira scope.

**Comment by theelstner** [comment]
14890986b2dff70c2787f782c474cdb342c08678
Deleting the copying-step of the model to /mnt/nfs/tira was ok, because we already mount the locally mounted tira model from outside he container via [Makefile](https://github.com/tira-io/tira/blob/14890986b2dff70c2787f782c474cdb342c08678/tira-host/Makefile#L38) to inside the container.

the error in step 19 is still not fixed, but does not stop the container from working: we tested vm create within the local container and logged in via the interface (the application needs a restart to accept the new user's login).

**Comment by MattiWe** [comment]
We have decided to leave the hosts dev setup as it is right now. 
A completely local setup is currently difficult due to dnsmasq and the routing of ssh requests into the VM. Without an update to the networking of the VMs, the host's local setup cant be simplified.
We recommend developing the tira-host on a tira-host machine (see the host salt state or contact devs to get it).
