### ISSUE TITLE
Enhance userdocs with easily updatable video

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#111]
There is a [video tutorial](https://www.youtube.com/watch?v=Wa2au1EvUJQ) that describes an exemplary use of TIRA as a user who submits a run from start to end. This is a great overview on what there is to do for first time users of the platform.

TODO:
- [ ] Reproduce this video on the current tira platform (new interface...), while
- [ ] using [this tool](https://webis.de/downloads/theses/papers/dunkel_2020.pdf) for generating spoken lectures from scripts

Using this software, thedocumentation video becomes easily updatable, when TIRA changes. See also this
[example Video] (https://www.youtube.com/watch?v=699e_l6XDI8&list=PLgD1TOdHQCI_R9aX5MvoM8kMqz_YECTke)done with this software.

**Comment by MattiWe** [comment]
Superseeded by Maik's work, i.e. https://www.tira.io/t/screencast-for-participants/886
