### ISSUE TITLE
Integrate Run-File Upload into the new TIRA frontend

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#112]
The goal of this task is to integrate the run file upload that we have used during the SCAI shared task.
We must be able to enable and disable the run file upload on demand.

We discussed the following things:
- The task configuration gets a flag to enable or disable run file uploads for the shared task
- Additionally, we use discourse groups to enable run file uploads for specific users: a user in a group "tira_upload_enabled_task" can upload to a shared task with the name "task". (ToDo: I have to ensure that the naming scheme of the discourse group conforms to what we had before).

**Comment by MattiWe** [comment]
Can you have a look at this when you get bored, Bastian?

**Comment by BastianGrahm** [comment]
> Can you have a look at this when you get bored, Bastian?

I actually already have a branch for that. Wanted to wait for the database to be in place though to not do something that gets thrown out of the window.
The html stuff for it is already done as a first version.
