### ISSUE TITLE
test if appllication works in deployment with disraptor

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#121]

**Comment by BastianGrahm** [comment]
Had to make a little adjustment in Disraptor to make it work with the csrftoken-system Django uses, i.e. the `csrftoken`-cookie has to be set when Disraptor `POST`s something to the application. Works fine now. So far so good. 
All pages loading and do stuff just like in local setup. No problems with dynamic element creation, e.g. on the software page.

Few visual bugs.

**Comment by BastianGrahm** [comment]
As mentioned in #127 there were Discourse login issues in combination with the application due to multiple instantiation of jQuery.js. This is solved by a fix in Disraptor.
