### ISSUE TITLE
`Power on` button does not work on first use

### ISSUE THREAD

**Issue by floebe** [tira-io/tira#140]
### key issue
The button `power on` does not work for the first time. When I click on `power on` for the first time, for some seconds the state is `powering on`, then again `stopped`.

### behavior on Nov 14
Continuing from the key issue, I observe varying behavior. 
* case 1: like on Nov 13 (see below), page reloads don't help, but a second click on `power on` leads to `running`
* case 2: a simple page reload helps

Full details until Nov 14, 14:00 are in this https://github.com/tira-io/tira/issues/136#issuecomment-968283992.

It seems problematic that I cannot predict which case appears when. Originally on `authorship verification 2021`, case 2 became possible after going through case 1. But on `author clustering` and `triple scoring` case 2 applied directly. Then again, `Style Change Detection 2021` ran into case 1 (and subsequent case 2 not explored due to a lack of time).

### behavior on Nov 13
Continuing from the key issue, clicking `power on` again works as expected and the state changes to `running`. 

**context**
* vm `test-user-03` on host `betaweb083.medien.uni-weimar.de`
* task `authorship verification 2021`

### expected behavior
State `running` is reached after first use of button `power on`.

### related
* #141

**Comment by floebe** [comment]
updated the issue with additional observations, where the behavior was close to as expected, but not reproducible directly on another task

**Comment by floebe** [comment]
updated with reconfirmation of original issue, by reproduction

**Comment by floebe** [comment]
## updates
updated the issue with new observations -> please read it anew from the beginning

## outdated details, just for reference
### additional observations 1
I could reach the expected behavior after I had managed to stop the vm. More precisely, at the stopped vm, I started it again with ´power on´. Then I reloaded the page and got state `running` - as it should be. In that state I could also shut down properly, clicking `shut down` once (relates to #141).
Trying to repeat this on another task, I selected ´Author clustering´, clicked ´power on´ and reloaded the page (3 times). The state remained `stopped´ - as reported above as current behavior.

**context**
* vm `test-user-03` on host `betaweb083.medien.uni-weimar.de`
* task `authorship verification 2021`

### additional observations 2
After Maik [reported](https://discord.com/channels/370896441863962626/640623874156920856/909194941677338626) the successful update of the frontend, I could reproduce and thus can reconfirm the original issue:
* `power on` yields `stopped` upon 1st use
*  on 2nd use the vm reaches state `running`

**context**
* vm `test-user-03` on host `betaweb083.medien.uni-weimar.de`
* task `authorship verification 2021`

**Comment by MattiWe** [comment]
I probably know why this happens, will investigate tomorrow.
