### ISSUE TITLE
Forward/backward navigation needs page reload to render tira content

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#142]
Using the back (or forward) button from a discourse page to get back to a tira page does not load the tira page. Instead, a blank page is shown. Reloading the page loads the tira page.

Edit: Going back to a vm-page from a different vm-page also has this effect. 

I tried to:
1. Go here https://www.tira.io/task/celebrity-profiling/user/test-user-04
2. click on any forum in the 'Forum' dropdown
3. click the back button 
4. reload the page

**Comment by mam10eks** [comment]
I see, this has been resolved in the meantime.
