### ISSUE TITLE
VM state is not always displayed correctly in interface

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#146]
**Current behavior**
VM state can be displayed as stopped of running in the interface, checking with ssh, however, shows that the machine is not always in the state displayed in. (Could ssh into so-called stopped vm, and could not access running vm). Reloading the page seems to fix the error. Waiting did not work (waited 2 minutes for it to change the state on its own).
Might relate to issue #140 

**Expected behavior**
State should be displayed correctly: running, when running, stopped, when stopped.

**Comment by MattiWe** [comment]
should be also fixed by #150 
Please open a new issue if you encounter this problem again.
