### ISSUE TITLE
Software does not run

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#149]
**Current behavior**
Submitted software changes the state of the vm in the interface from "running" to the loading wheel. Nothing seems to happen, even after waiting 8 minutes.
<img width="1335" alt="Bildschirmfoto 2021-11-16 um 18 25 09" src="https://user-images.githubusercontent.com/12912413/142035570-c6e02a1b-e1ec-417d-9e14-3b2064c9f6e5.png">

**Expected behavior**
The state should change according to whats done + tira should do what it is supposed to do: cloning, sandboxing, executing the script.

**Comment by MattiWe** [comment]
I can reproduce this, but not consistently. For me, the VM actually does the sandboxing and executes the software. 

The host logs tell me stories of `InactiveRpcErrors` with `failed to connect to all addresses` and `Failed to pick subchannel`. That means the host sometimes fails to respond to the application. If the host fails in the 'confirm request' part, you get a spinner. I think this has to do with #150.

**Comment by MattiWe** [comment]
I will close this for now, since#150 was fixed. If the faulty behavior reoccurs, please open a new issue.
