### ISSUE TITLE
Run Software should not allow Input Dataset = None

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#153]
**Current behavior**
When I run a software without changing the Input Dataset, it uses the default "None".
The run seems to start, but after it is finished, I can not inspect the dataset.

**Expected behavior**
I would expect that I can not run the software on "Input Dataset = None".

**Comment by MattiWe** [comment]
I've added this. Your now shown an error message when inputDataset is None or if command is empty.

**Comment by MattiWe** [comment]
I've added this. Your now shown an error message when inputDataset is None or if command is empty.
