### ISSUE TITLE
The creation of discourse groups is not working anymore

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#157]
**Current behavior**

**Expected behavior**

**Comment by BastianGrahm** [comment]
API change again? Is there any feedback?

**Comment by BastianGrahm** [comment]
I think the Disraptor App Secret Key might have changed.

**Comment by BastianGrahm** [comment]
Okay I think I figured it out.
Since the API key we use for group creation can be used by all users (don't worry it's still our secret and only admins can do admin stuff) you have to give a header called `Api-Username`. Reading from https://github.com/tira-io/tira/blob/2ba5887b98047ad6d50aa844f096f490f6bc21a0/tira-host/src/tira_scripts/discourse-create-vm-group.sh#L63 I don't think we do that yet.
This can be any admin username. Probably `system` fits best.

**Comment by mam10eks** [comment]
Oh, sorry, this was meant on a different level xD

I didn't fully wrote what I meant, sorry for that, I meant that the old java-backend (that we used for submitting this calls) is not available anymore, so I can not issue new groups right now.

**Comment by BastianGrahm** [comment]
Oh. :sweat_smile: Anyway I think it still might be relevant. Issuing API calls without the `Api-Username` header didn't work for me. Atleast not when doing admin stuff.

**Comment by mam10eks** [comment]
Ok, maybe we have two issues xD

I now have it running, and it does not work because it says `date: invalid date 'next year'`.
You are currently on this? Could you please have a look?

**Comment by mam10eks** [comment]
One additional note: This seems to happen when the invite link is created.

**Comment by BastianGrahm** [comment]
https://github.com/tira-io/tira/blob/2ba5887b98047ad6d50aa844f096f490f6bc21a0/tira-host/src/tira_scripts/discourse-create-vm-group.sh#L77

**Comment by mam10eks** [comment]
Ah, thanks, good catch, now it works

**Comment by mam10eks** [comment]
- From the discussion: We create a REST-Endpoint (@MattiWe describes where), and then we document for the moment: just go to the URL https://..../USER

**Comment by mam10eks** [comment]
I now have added the respective endpoint, but it looks like the REST-Call is not forwarded to the backend.
I find such entries in the log: `WARNING 2021-12-10 18:01:42,510 log: Forbidden (CSRF cookie has incorrect length.): /tira-admin/admin_create_group`

@BastianGrahm I think this is because of we have to add a disraptor route?
The route is: `https://www.tira.io/tira-admin/admin_create_group`

And after we have added this route, we have to restart discourse?

**Comment by MattiWe** [comment]
Thats probably not it. We have wildcard routes for get/post to tira-admin and below.

**Comment by mam10eks** [comment]
It looks like disraptor does not set the csrftoken-Cookie. Can this be?
I looked into the network activity of my browser, and my browser does not send a csrftoken Cookie.
Hence, the server thinks it is unauthenticated and the failure above is correct.

With curl, I can construct a valid request which receives a 200 response.

E.g., my curl statement is something like this (executed in the pod):
```
curl -i -X POST -H 'X-Disraptor-Groups: admins' -H 'X-Disraptor-App-Secret-Key: <OMITTED>' -b 'csrftoken=<OMITTED>' localhost:80/tira-admin/admin_create_group/<VM-ID> --data-raw 'csrfmiddlewaretoken=<OMITTED>&vm_id=a'
```

There I actually get a response 200-response with the expected invite link and everything works.
It also looks like the URL that the frontend is calling is wrong, since the URL does not add the `/<VM-ID>` suffix and only calls `/tira-admin/admin_create_group/`.

This has no high priority, since I can work with the curl statement mentioned above.

**Comment by MattiWe** [comment]
> It also looks like the URL that the frontend is calling is wrong, since the URL does not add the /<VM-ID> suffix and only calls /tira-admin/admin_create_group/

No, that's correct. There is a GET and a POST [endpoint](https://github.com/tira-io/tira/blob/dc22c5bda66761449ce41f33d571f58f8c00b6e4/tira-application/src/tira/urls.py#L46). The GET endpoint needs the ID, the POST endpoint does not. The form is submitted via POST. 

There are also different methods called.

**Comment by BastianGrahm** [comment]
Are you adding the csrftoken to the headers like so?
https://github.com/tira-io/tira/blob/dc22c5bda66761449ce41f33d571f58f8c00b6e4/tira-application/src/tira/static/tira/js/tira-admin.js#L44-L46

**Comment by MattiWe** [comment]
OK. I changed the way the token is set. Can you test the group creation via admin panel and via API call again?

**Comment by mam10eks** [comment]
Yeah, very nice, it is working now as expected.

The response has a message that contains an invite link that we send to the participants.
Is it easy to open a popup that shows this response message?

Currently I am extracting this invite links from the "network" tab of the browser dev-tools.

**Comment by MattiWe** [comment]
i've added a modal dialog for this.
