### ISSUE TITLE
The frontend does not update the available vms

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#158]
**Current behavior**
I create a new virtual machine, click in the frontend the admin button for reloading the cache, but when I try to access the VM on a task page, I get the "Page does not exist error".

In the log file I get `software-detail: vm_id does not exist`.
I restarted the frontend, and then it works again.
But it might be not acceptable to always restart the frontend for each and every new virtual machine.

**Comment by mam10eks** [comment]
I recognize this issue when I want to create the discourse group for the virtual machine via the frontend (using the new form).

When I restart the frontend, creating the disclosure group works.
It looks like the VMs are cached somewhere, and reloading the cache in the admin UI does not solve this.

**Comment by MattiWe** [comment]
Ok, I've added watchdog to reload the data on change. The reload button should not be necessary anymore with this. 
@mam10eks Can you test if this resolves your problems?

Note that we loose a lot of performance with this and it should be highly! temporary.

**Comment by MattiWe** [comment]
should be solved by 210e97c06a4ce5339d47657dd059d1ca57130d5f
Please create a new issue if the issue reoccurs
