### ISSUE TITLE
The frontend should show the CommandDescription to users

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#161]
The old version of tira showed the `commandDescription` and `commandPlaceholder` to its users.
I used both previously to explain how users should build their commands for the specific shared task.

E.g.:
```
commandPlaceholder: "mySoftware -i $inputDataset -o $outputDir"
commandDescription: "Commands should take the arguments <code>$inputDataset</code> and <code>$outputDir</code>. The variable <code>$inputDataset</code> points to a directory that contains a <code>topics.xml</code> file that contains the topics for which documents should be retrieved and a file <code>passages.jsonl.gz</code> that contains all the passages. Your software should create a standard trec run file in <code>$outputDir/run.txt</code>."
```

In the current version, it seems like the frontend shows an generic placeholder:

![Screenshot_20211209_153123](https://user-images.githubusercontent.com/10050886/145416293-436aaabf-3f36-40b2-89f8-c0de312b7391.png)

I think it is helpful for users to show task-specific hints like those specified in the `commandDescription` and `commandPlaceholder`.

**Comment by mam10eks** [comment]
Example: `/mnt/ceph/tira/model/tasks/touche-task-2.prototext`

**Comment by MattiWe** [comment]
I've changed it so that, in the default scenario, it uses the current solution
![image](https://user-images.githubusercontent.com/9336644/145601148-b5da8400-326d-4a87-ad94-533d5eeee767.png)

Otherwise it displays the custom commands:
![image](https://user-images.githubusercontent.com/9336644/145601233-92b08fc1-b201-45c4-acd4-ab4a31eb6a08.png)

**Comment by MattiWe** [comment]
@mam10eks U happy, can I close tihs?

**Comment by mam10eks** [comment]
Yes, I am happy :)
