### ISSUE TITLE
Users should see the output/run/stderr of training runs without unblinding.

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#162]
I have created a training dataset, where users should be able to access everything by default, but it seems like the users have no access to the run. I must first unblind it, but for training data users should be able to access everything on their own:

![Screenshot_20211209_154129](https://user-images.githubusercontent.com/10050886/145417553-b4aeb742-a1ac-4d58-9cb7-897ad2d17702.png)

It is possible that I have a configuration mistake, but I looked up everything two or thee times:

- `/mnt/ceph/tira/model/tasks/touche-task-2.prototext` has the dataset listed as trainingDataset
- the data itself is available in `/mnt/ceph/tira/data/datasets/training-datasets/touche-task-2/touche-2022-task2/`
- `/mnt/ceph/tira/model/datasets/touche-task-2/touche-2022-task2.prototext` has the flag `isConfidential: false`

**Comment by MattiWe** [comment]
I've added this as a default behaviour. 
Users now always see the output of their reviews if it is unblinded or if the dataset is not confidential.
