### ISSUE TITLE
Starting/Stopping a virtual machine via the frontend is a bit misleading

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#167]
When I start/stop a virtual machine via the frontend, I sometimes get weird behaviour:

- The VM is stopped
- I click on start vm
- It says it is starting the VM
- After some seconds it is back to "The VM is down"
- I click again on start the vm
- I get some error message in the frontend (internal server error)
- After reloading the whole page, I see that the VM is already started

**Comment by theelstner** [comment]
I ran into the same error with VM
- touche22-pearl

**Comment by theelstner** [comment]
On betaweb127 the start/stop behaviour is different than described for the machines above, but also buggy:

- after creating the vm, and first accessing it via the frontend (https://www.tira.io/task/touche-task-2/user/touche22-porthos), the state of the vm was "stopped" and the rdp-port was "closed", BUT: the ssh-port was "open". the state was correct, as i could ssh into the vm, but still this should not be.
- also: the  vm cannot be powered on. after clicking "power on", it's state goes to "powering on" and then switches to "stopped" again. the states of the rdp (closed) and ssh ports  (open) remain unchanged.

**Comment by MattiWe** [comment]
Is this still a problem? @theelstner

**Comment by theelstner** [comment]
I have checked with https://www.tira.io/task/touche-task-2/user/test-user-01 that is the only vm on betaweb127. This VM cannot be powered on, I suspect this is related to the error before.

**Comment by MattiWe** [comment]
> I have checked with https://www.tira.io/task/touche-task-2/user/test-user-01 that is the only vm on betaweb127. This VM cannot be powered on, I suspect this is related to the error before.

No, that was me. I fixed that. I also checked, and the initial wrong behaviour from mike is still there.
