### ISSUE TITLE
Popup: Saving Software software1 responded with: Not Found {"failed":"FAILED"}

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#172]
Saving a software seems to fail: I get a popup that says it is failed.

- When I reload the page the changes seem to be persistent
- When I click on Run Software, multiple errors pop up
- After clicking on run software and reloading the page, the software seems to be deleted

**Comment by MattiWe** [comment]
propabaly fixed by a393f121fdf75e32fde75281602fa7a9b7e613cb

**Comment by mam10eks** [comment]
@MattiWe I have deployed the version with your changes above as `0.0.10`, and the problem mentioned above seems to be resolved.

Still, the behavior in the frontend seems to be inconsistent over multiple reloads of a page.
Maybe this is caused by the multiple processes that run the frontend code which may cause some inconsistencies?

E.g., the current behavior is:

- I can save and create a new software
- If I reload the page multiple times, the new software is sometimes there, sometimes it is missing
- I get error messages when I click on execute run, this might be caused by the inconsistencies mentioned above (since it looks like not all processes know about the run, and maybe a process that does not know the run gets the "execute run request"?) I tried it multiple times, in the frontend it always seemed like no run was executed, but I am not sure, because the state of the virtual machine was also not stable across multiple page reloads, so it can be that the software did actually run.
- I also have problems with deleting a software (maybe also caused by the inconsistencies across multiple processes?)

**Comment by MattiWe** [comment]
I have a server-side 'does-the-resource-exists check for all actions. All of the above would be explained by this. I'll work on a better solution over the next week.

**Comment by mam10eks** [comment]
I thought a bit, and the only reasonable solution that came to my mind was to use a database. I am not really into the Django framework, but probably there are already some ORM modules that make the data access very simple?

**Comment by mam10eks** [comment]
@MattiWe can you estimate how long it takes until this is resolved?
Would setting the number of processes to 1 be a suitable workaround for the moment?

**Comment by MattiWe** [comment]
a day or two

**Comment by mam10eks** [comment]
Nice, thank you!

**Comment by MattiWe** [comment]
should be solved by 210e97c06a4ce5339d47657dd059d1ca57130d5f
Please create a new issue if the issue reoccurs
