### ISSUE TITLE
Filtering the overview of shared tasks does not work when the page is reloaded or the url is copied

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#176]
**Current behavior**
When I filter the task page or copy a URL that filters for some shared task, the task overview page is empty.
- e.g., for https://www.tira.io/?q=scai it shows me now results (when I directly navigate to this URL or reload the page. It is working when I start with https://www.tira.io/ and filter there for "scai").

**Comment by BastianGrahm** [comment]
This seems to be related to Discourses behavior when we override the `/` page.
I tested it with mapping the root page to `/test` i.e. I then called `/test?q=scai` and it worked perfectly.

For later reference, this is what the log says:
```
Started GET "/latest?q=scai" for 95.90.182.105 at 2022-02-03 12:31:53 +0000
...
Processing by ListController#latest as */*
  Parameters: {"q"=>"scai"}
...
```

**Comment by mam10eks** [comment]
https://github.com/tira-io/tira/projects/
