### ISSUE TITLE
The "Add Software button" does not close the dop down when clicking on a different software

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#178]
**Current behavior**

On a virtual machine page, clicking on add software opens some dropdown.
The current behaviour is, that this dropdown stays open when I click on different software, but I would expect that the dropdown closes because I have clicked on something outside the dropbdown.

**Comment by BastianGrahm** [comment]
Tested this in codepen.io.
It's due to the uikit.js version webis is using. 
We use version 3.0.0rc20 while the current version (in which it works) is 3.10.0.

Best I can do right now is making it pop out on hover. Then it vanishes when it is not hovered anymore.

**Comment by MattiWe** [comment]
> Best I can do right now is making it pop out on hover. Then it vanishes when it is not hovered anymore.

That may be the preferred way anyways?

**Comment by BastianGrahm** [comment]
I think so too. I was just wondering, why it was opened with click in the first place, since hovering is the default behavior.
Anyway I pushed a fix.
Will close this.
