### ISSUE TITLE
The Run Software button is only clickable after reloading the page

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#179]
**Current behavior**

I add a new Software and save it. Still, the run button is not clickable and remains grey. After reloading the page, the run button is blue and I can click it.

**Expected behavior**

The run button should be clickable as soon as the software is valid (and maybe saved).

**Comment by MattiWe** [comment]
Actually, that button should get activated whenever the VM switches to 'running'. However, creating a new software does not toggle that check. I've added a check on dataset selection and command change, which now tells you frontend-side what you need to do. 

The perils of not using a ViewModel with databinding...
