### ISSUE TITLE
top navigation bar looks empty on (some?) error pages

### ISSUE THREAD

**Issue by floebe** [tira-io/tira#190]
## Current behavior (Feb 23, 2022)
**Summary**
On certain error pages, the top navigation bar looks completely black and thus empty, but contains 1 (?) clickable area.

**Further details**
During several tests on Feb 23 that resulted in error pages, say, due to producing a URL in the browser address bar for which there is no page (cf. screenshot), the navigation bar seems missing/empty. However, at the position expected for the TIRA icon, there's still a clickable link (area) that leads to the frontpage (which is then displayed correctly).
> --< screenshot starts here >--
![partial screenshot](https://user-images.githubusercontent.com/55153781/155352636-86ec82f0-78e6-487e-82a1-57a5a905a8c5.png)
> --< screenshot ends here >--

This applies to pages that are missing as well as to pages that exist, but for which the user has no access rights.

**Side remarks**
FL vaguely believes that we have seen (and perhaps discussed) this behavior before, but after a bit of searching I could not find an existing issue - thus creating this one.

## Expected behavior
The top navigation bar remains available on error pages.

**Comment by BastianGrahm** [comment]
![image](https://user-images.githubusercontent.com/29681076/155509119-5f17a8fe-b9c2-4432-b11f-7b56e9d8daa0.png)
This is how it looks on the official Discourses forum.

Notice how only the logo remains.
The logo not appearing for us on that error page is linked to #116 and will be resolved as soon as #116 is resolved.

Will close this for now.
