### ISSUE TITLE
Run doesn't show at the leaderboard (incl. counting of runs vs submissions unclear)

### ISSUE THREAD

**Issue by floebe** [tira-io/tira#191]
### Current behavior
- FL produced the run https://www.tira.io/task/touche-task-1/user/frank-loebe/dataset/touche-task-1-2022-02-16/run/2022-02-24-14-55-00
- TE does not see that run at the leaderboard:
  ![grafik](https://user-images.githubusercontent.com/55153781/155565224-ddac0c33-a65e-4cc6-8a5f-088de0ff9717.png)

### Expected behavior
- The run is expected in the leaderboard.

### Related questions
**How do the following three figures relate to each other and what does "submissions" count?**
- The [touche-task-1](https://www.tira.io/task/touche-task-1) overview displayed "(10 submissions)"
    This applies after the specified run was submitted, the first run on that task on the VM `frank-loebe@betaweb121.medien.uni-weimar.de`. Before, it showed "(9 submissions)".
- The leaderboard screenshot lists 4 VMs with different runs that add up to 12.

**Comment by MattiWe** [comment]
A submission is a run (i.e. executing some software and producing an output) and an evaluation of said output. The evaluation may be skipped. 
The leaderboard shows evaluations that have been published by a reviewer.  

I will clarify the terminology while updating the task view. See also #196
