### ISSUE TITLE
Create VM (for a user) fails on betaweb127

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#199]
**Current behavior**
Following the instructions on [how to create a vm for a user](https://github.com/tira-io/tira/wiki/Organizing-Tasks) on betaweb127 `tira vm-create tira-ubuntu-20-04-server-64bit.ova debug-issue167` fails and never finishes after tira vm-start:

<img width="1023" alt="Bildschirmfoto 2022-03-03 um 14 50 56" src="https://user-images.githubusercontent.com/12912413/156579735-419985ba-1fb2-4609-bbf9-b61e5a123f08.png">

However, tira vm-list shows the vm. Creating a corresponding discourse group fails:
<img width="671" alt="Bildschirmfoto 2022-03-03 um 14 52 59" src="https://user-images.githubusercontent.com/12912413/156580102-8e85b316-e795-4718-a766-a05ce55c9cfb.png">

I have not checked, whether this is also a problem on other hosts

**Expected behavior**
Creating vms for a user should work.

**Comment by MattiWe** [comment]
Stale. Create a new issue when the problem reoccurs.
