### ISSUE TITLE
Evaluator runs only visible after manual page reload

### ISSUE THREAD

**Issue by theelstner** [tira-io/tira#200]
**Current behavior**
(Running the evaluator triggers and automatic reload of the page. The software tab is changed to the first software instead of the one the evaluator was run on.)
After going to the software the evaluator run was performed on, the evaluator run is not visible. A manual page reload makes it visible.

**Expected behavior**
Evaluator run should be visible without manually reloading the page.

**Comment by MattiWe** [comment]
That may be a race condition. I would, for now, try to add a 5-second sleep to the function that reloads the page.

**Comment by MattiWe** [comment]
yeah. 
I suspect the parsing-into-the-database of the results takes longer than reloading the website, so the website shows the old state. 
I have to check tomorrow how we can solve it serverside, but if you change that line (in the browser), you can check if I'm right.

**Comment by mam10eks** [comment]
I would favor the server-side solution because the 5-second wait on the client is hacky and testing the 5-second approach would not give us new information (waiting X seconds will work, because reloading the page currently also works).

**Comment by MattiWe** [comment]
#0d20d1fde27eb104a9a31389291474a5bdc50cfc should fix it.

**Comment by MattiWe** [comment]
https://github.com/tira-io/tira/commit/0d20d1fde27eb104a9a31389291474a5bdc50cfc
did not fix it, but e91a4c03fde395f303f1826d63cb11270b9b20a4 did (the hacky way). Since this works for now, I'll leave it at that and do a proper fix after converting that page to vue.js
