### ISSUE TITLE
Labels in edit modals are displayed incorrectly on disourse

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#209]
**Current behavior**
![image](https://user-images.githubusercontent.com/9336644/163224979-a31a4400-5bbc-40df-87a7-8183a54ab52d.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/9336644/163224933-c3d718c7-0540-4018-a628-68bd616596ee.png)

**Comment by BastianGrahm** [comment]
Looks like this is due to this display option of the label set to flex by some discourse css.
![image](https://user-images.githubusercontent.com/29681076/163227516-f174248a-2b64-48d2-a819-2e092de37595.png)

If I disable this is looks (almost) as intended.
