### ISSUE TITLE
Empty modals on the live version

### ISSUE THREAD

**Issue by BastianGrahm** [tira-io/tira#210]
**Current behavior**
Sometimes the modals for e.g. task creation that should be filled with content by Vue.js on pageload are empty on the live version.
![image](https://user-images.githubusercontent.com/29681076/163416467-510b2a6e-573c-47ae-875f-86f367bfe8f8.png)

**Expected behavior**
It should look something like this
![image](https://user-images.githubusercontent.com/29681076/163416604-5eeb2729-a11d-4ca1-aed3-a0cdd1dba4d6.png)

**Reason**
This seems to be a race condition problem.
On the page there is a `script` tag with `src="https://unpkg.com/vue@3"` which get loaded asynchronously and a inline module-script tag containing  the Vue code.
Now if the module code is executed before the Vue.js script is loaded from unpkg an error will be thrown telling that Vue isn't available. The module is then never re-executed and the modal is never getting filled.

**Possible solutions**
The first solutions that come to mind are:
1.  deferring the module code by waiting a short amount of time (probably instable)
2. putting the module code in an external script and then putting `<script type="module" src="/path/to/external/script.js"></script>` instead.

I'm not too sure about the success of option 2 but it would be way cleaner than 1 and this worked before.

**Comment by MattiWe** [comment]
If any of these solutions is fast and stable, then we can do those. 
The best option is actually to use webpack to build vue, then we don't need to load the vue lib with each call. It would also make the site faster. 
https://dev.to/clifinger/django-and-vue-3-0-with-webpack-loader-and-typescript-support-5e6h

**Comment by mam10eks** [comment]
This might also be related: https://github.com/tira-io/tira/issues/237

**Comment by MattiWe** [comment]
fixed with the webpack builder
