### ISSUE TITLE
Adding a new Task does not work

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#237]
**Current behavior**
The dropdown to select an organizer is empty.
So when I click on "Add Task", the validator says that I need to select an organizer from the empty list of organizers (which is not possible) and hence I can not add the new task.

**Expected behavior**
The list of organizers should be not empty, or it should be allowed to submit a task without an organizer.

**Comment by MattiWe** [comment]
is this https://github.com/tira-io/tira/issues/210? Did you try to reaload?

**Comment by MattiWe** [comment]
Because it works for me on live.

**Comment by mam10eks** [comment]
Ok, weird.

If I reload the page it works now. Maybe this is some side effect with disraptor?
I cant remember what I did before on the page, when I freshly reload it it works, but before it failed.

Do we investigate this further?

**Comment by mam10eks** [comment]
Ah, ok, so it seems like #210 is the issue.
