### ISSUE TITLE
Use systemd-resolved instead of dnsmasq

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#24]
- Remove dnsmasq service
- Remove dnsmasq commands from the tira scripts
- IPTables: FORWARD from all TIRA interfaces to lo.
- [ ] Test this on betaweb111
     - Creation of new VM (and in old VMS)
     - Existing VMs

**Comment by MattiWe** [comment]
We decided to postpone this until we want to rework the VM's networking more thoroughly.
