### ISSUE TITLE
Discussion: Should we delete Software/Runs in TIRA.io?

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#257]
A discussion item for the next meeting.

From a mail by Johannes: 

```
Should we allow people to delete their runs at all? Maybe it makes sense to have something like: if you did not delete it after a day (or some specific date after a shared task's deadline), it can only be deleted upon request to us as TIRA maintainers (for severe cases)? If we want people to build new software based on existing TIRA software, we may want to avoid people deleting their stuff arbitrarily?
```

My opinion: I would like it when people can still delete their software and runs, but we only store a "deleted" flag in the database so that we do not delete anything and can restore everything.

**Comment by MattiWe** [comment]
Originally, we never deleted runs or software and just 'hid' them with this flag. We changed this to the current (delete it) behaviour, because we ended up with an extreme amount of failed runs (up to 100 per user). 

I suggest, we prevent deletion of runs or software once they have been (a) reviewed as 'valid submission' or even as 'published on leaderboard'

**Comment by MattiWe** [comment]
Behaviour is now as follows:

- Deleting Software is always allowed. 
- Deleting Software also deletes all runs and reviews. An appropriate warning is shown. The on-file runs are kept as backup and can be deleted when the task is archived. 
- Deleting a Run is prevented when
  - This run is used as an input run (i.e. if there is an evaluation of this run). The dependent run must be deleted first. 
  - The run is published on the leaderboard
  - The run has been reviewed as 'has no errors'

This allows participants to delete failed or extra runs but forces them to keep all necessary runs. 
This also allows participants to delete all traces if they get problems (are not allowed to publish their software, GDPR, whatever) with the appropriate consequences.

**Comment by potthast** [comment]
Just deleting everything related to a software feels unsafe, even with an warning.

Also, keeping runs for deleted software seems reasonable for industry folks who want to expose their software to us only temporary.

**Comment by MattiWe** [comment]
> When I delete a software with a published run, does it then delete the software and keep the run? I am not sure from your comment.

Deleting Software also deletes all runs and reviews. So yes, including published runs. Software here means the 'settings' like the command and working dir, not the stored code. 

From your suggestions, it is perhaps better to:
- Prevent that a Software (i.e. the settings) is deleted once there are valid runs (i.e. with a correct evaluation)
- Allow users to delete the docker image from our registry (via tira.io)

**Comment by MattiWe** [comment]
Update as discussed:
- there is a confirmation popup for `big` deletes
- delete buttons are a more out-of-the-way
- software can not be deleted if the is a dependent (successful) evaluation
