### ISSUE TITLE
Run Uploads: Directly start the evaluator

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#268]
As shortly discussed with Bastian, when users upload a run and the task has the tira-git-pipeline enabled, then the evaluator should be directly started.

This should be done on the server, so the last thing that the REST endpoint that uploads the file should do, is check if the tira-git-pipeline is enabled, and if it is enabled, it should use the run-id of the uploaded run to start the evaluation.

I refactored a utility method to check if the tira-git-pipeline is enabled for a task: https://github.com/tira-io/tira/blob/development/application/src/tira/tira_model.py#L121

**Comment by BastianGrahm** [comment]
solved, see 584911f329373c0fbbcdbf88b4eb0a93d9cc11e6
