### ISSUE TITLE
Docker Submission Tab should not make rest calls if docker submissions are not enabled for a task

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#272]
If docker submissions are not enabled for a task, then the frontend still makes REST-Calls which are shown as errors in the frontend.
The frontend should not make REST calls if no docker submissions are enabled for a shared task.

![Screenshot_20220924_102028](https://user-images.githubusercontent.com/10050886/192088275-0cb022c6-d764-4931-baf3-f2e938e4744a.png)

**Comment by BastianGrahm** [comment]
That are calls to create a software in the VM page.

**Comment by BastianGrahm** [comment]
This is fixed with the new image due to commit https://github.com/tira-io/tira/commit/dfc2f6b842e8178e828f8d0c2d47208f7d88b7de.
Closing.
