### ISSUE TITLE
Usability Enhancement: The Layout for adding a docker software should show the help provided by the task

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#273]
Right now, the form for adding a new docker software does not show the help provided by the task:

![Screenshot_20220924_103009](https://user-images.githubusercontent.com/10050886/192088631-002c5807-7c84-4cfe-b822-bb15f34dd034.png)

But useful information is available. For instance, we have for each task the help command and the help text as specified here:

![Screenshot_20220924_102927](https://user-images.githubusercontent.com/10050886/192088701-ba9f625b-c47b-443c-9176-dcff3a034f77.png)

The form should show the help command inside of the command input (as it currently shows something like `cat ...`).
And the help text should also be displayed there.

**Comment by Dumpling97** [comment]
ffdc937 implemented showing both the help command and the help text
