### ISSUE TITLE
Runs submitted and evaluated via the tira-git-pipeline do not appear on the Leaderboard.

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#275]
Although the runs are reviewed and unblinded and the evaluations generate reasonable results:

![Screenshot_20220924_220846](https://user-images.githubusercontent.com/10050886/192116566-1937c80b-f38a-4b57-b8f8-36cdd03b9f0e.png)

they do not appear on the leaderboard.

**Comment by MattiWe** [comment]
@mam10eks If this is fixes with 6fdc5ee961c898db4a78c3b76ed06a7a23048e3a please close

**Comment by mam10eks** [comment]
Yes, indeed, this is fixed now.
