### ISSUE TITLE
How to Add Discourse Accounts to a Group in Retrospect

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#278]
People might submit to TIRA without being associated to a group.

For that reason, we need to handle such submissions in retrospect.
This ticket aims at producing a strategy on how we should handle this (cc @MattiWe, @potthast).

The first thing that comes to my mind is:

- We create a Prometheus alert that fires if there are submissions to a shared task that do not belong to a group
- If we get such an alert, we contact the corresponding user to figure out to which group the user belongs. In this process, we maybe create a new group for this user, or maybe we already know from their account/name/mail to which group they belong.
- We fill out a short form in the frontend, like "Add User X to group Y". The frontend should take care of the following:
  - Create the group (if not already existing)
  - Move existing runs and evaluations of the user to the group
  - Move existing software submissions of the user to the group

We can also discuss if we want to solve this completely different?
E.g., we could ensure that users cant submit if they do not belong to a group?
This would require small changes in the frontend, but maybe would be better because we do not have to clean up in retrospect?

E.g., we could add the usual link to the registration for a shared task to the details that we store in TIRA on shared tasks.
Then we could show to users a small form if they do not belong to a group: "Register Now", "I already Belong to group: <fill this out>", "I forgot my group/Contact organizers".

**Comment by MattiWe** [comment]
I don't fully understand this. Why should we add them to a group if we don't need to?

**Comment by mam10eks** [comment]
I do not think that user-level auth is enough for uploads and docker submissions, because this would mess things up.

E.g., what if people from the same group use different accounts for their upload? We would have to fix this in retrospect, which would even be more severe when we want to make everything available after a shared task.

For instance: assume that we have a user A and B, both registered in a google form as group C. But if we do not have this reflected in TIRA we get a mess. I.e., if users A and B submit as group C in TIRA, everything is fine. But at the moment, they would submit as A and B independent of each other. We would have to manually resolve this with quite some effort (renaming already submitted software, runs, evaluations, etc.) so that the final archive at the end of the shared task can be understood by others.

**Comment by MattiWe** [comment]
The thing is that, right now, we have little control over the assignment from groups to users (without enforcing it trough the VM process). This has the advantage that it is hands-off for us. We don't (technically) need the groups anymore. 

You want the groups to assign users to registrations (for management reasons). Here are some ways to do this without many implementations or forcing (all) users to fill out lots of unnecessary forms (because most users won't fall in your scenario):
- They could share credentials (no association between user and registration, cheap and fast)
- One of them is the designated uploader (as above)
- We have different uploads from different people under different names, we ask them registration time to map tira-accounts to groups for us. 
- We add a textbox to the submission page and ask for the group name. We add a checkbox to the task to enforce using this textbox. The textbox can be free-form or a dropdown of pre-defined group names.

**Comment by mam10eks** [comment]
I also want to have it as simple as possible.

But the current way introduces quite some work for us after a shared task (and in some cases it might even be possible that we can not correct everything in retrospect).

I mean: upon Registration, we always have some manual effort.
For instance, we remove the selected group name from the list of available groups manually.

There is some potential here to make everything more streamlined.
I mean, in the best case, participants can do everything without manual action from us.
With discourse, we already have proper group management, and also a survey plugin.

**Comment by mam10eks** [comment]
Maybe it would be enough if users can create a group on their own and then they become automatically admin of this group and with this they can invite others.

**Comment by MattiWe** [comment]
This could be well implemented without much recurring effort. 

I would still add the 'enforce submission in group' toggle for tasks, because not everyone may want this behavior.

**Comment by mam10eks** [comment]
We do not have to implement this fast, we can sketch such a workflow on paper, and then discuss it in the next TIRA meeting.

**Comment by mam10eks** [comment]
> This could be well implemented without much recurring effort.
> 
> I would still add the 'enforce submission in group' toggle for tasks, because not everyone may want this behavior.

So when a shared task is over, organizers than can switch this toggle to "allow whatever people want to do".

**Comment by MattiWe** [comment]
If we register groups with an external form, we have to prohibit registration to tira without an invite. I don't want this.

We could make a small 'registration' effort within tira.io. Before submitting to a task, you must 'register' or 'join' that task (i.e. fill out a small form that includes a group creation or group join).

**Comment by mam10eks** [comment]
Yeah, if we do something like this, this might also solve the problem of users that use or need multiple vms/groups across different tasks.

**Comment by mam10eks** [comment]
We discussed that adding a discourse group to accounts in retrospect is not useful.

Instead, we let people directly register to a new group and let them manage their group, and this is part of this ticket: https://github.com/tira-io/tira/issues/291
