### ISSUE TITLE
Explicitly show the timestamp for all cached components in the Frontend and give users a link where they can click to get a refresh

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#280]
We should make it explicit that certain parts of the application are cached.

E.g., the running software and the docker images are periodically refreshed.
To give full transparency to users, we should show a small text box that is transparent about this and gives users the possibility to refresh everything with a single click.

**Comment by potthast** [comment]
If the process to update runs in the background, the time until next cache update can be shown.
Of course, it should be prevented that people Spam the "Refresh Cache" Button causing trouble at our end.

**Comment by mam10eks** [comment]
The cache is task specific.

**Comment by mam10eks** [comment]
In the best case users dont have to ever refresh the cache, but it is still good to give users directly this possibility.

**Comment by potthast** [comment]
And knowledge about what's going on in the background. The more transparent we make TIRA's workings to the user, the better.

**Comment by mam10eks** [comment]
@Dumpling97 you are working on a very similar thing at the moment in the frontend, and I now have implemented the associated changes in the backend, so maybe you can directly add the corresponding changes to the frontend?

for both cached scenarios (docker images + running containers), I added the following fields: `running_software_last_refresh`, `running_software_next_refresh`, `docker_images_last_refresh`, `docker_images_next_refresh` that you can use to show the explained behavior.

Please also directly add a corresponding link for "refresh now".

Here is a short sketch where you might add the corresponding things.
Please do not hesitate to ask in case of questions.

New Information for the Docker images:
![Screenshot_20221031_110638](https://user-images.githubusercontent.com/10050886/198985169-8bb0c3e9-a900-40b3-9e31-495c6233db6c.png)


New Information for the running software:
![Screenshot_20221031_110958](https://user-images.githubusercontent.com/10050886/198985247-eb3aac4a-45a1-4e7e-9537-950efcacc3a3.png)

**Comment by Dumpling97** [comment]
I implemented showing the refresh times for the running processes in [f11e8cc](https://github.com/tira-io/tira/commit/f11e8cc26d0c2a1f8fa00f4162ca3ff925ca8e8b) .

It seems to only update the time when a new container is started or one finishes, not each time the running containers are polled. If I understood correctly however, the latter is the intended behavior, no?

**Comment by mam10eks** [comment]
Nice!

Yes, it should update the time every time when the running containers are polled.
Do you think this is possible?

The 10 vs 15 seconds thing is caused since the backend refreshes in 15 seconds intervals.

**Comment by Dumpling97** [comment]
The problem is as stated above. Using the times you implemented in the commits for this issue does not seem to work properly.

However, if we update the shown time every time the containers are polled, why don't we just show the current date directly at every poll instead of passing the time from somewhere else? It would result in the same thing if I haven't misunderstood.

**Comment by mam10eks** [comment]
What does not work?

I dont understand, the client should show what the server sends, we should not duplicate the logic.
The ticket is intended to add more transparency, and for that it helps if the user sees at which time the server would next refresh the time.

Furthermore, one aim of the ticket is also to add a refresh cache mechanism, e.g., the "Refresh now" button.
And then everything would be fine, or do I understand something wrong?

**Comment by Dumpling97** [comment]
> It seems to only update the time when a new container is started or one finishes, not each time the running containers are polled. 

This is currently the main problem.
If I start a container at 18:00 then the `running_software_last_refresh` stays at 18:00 until either another container is started or a started container finishes.

**Comment by mam10eks** [comment]
But it just uses the content from the server and the "refresh now" button works?

Then everything should be fine, maybe there is still a bug on the server side, that I can fix.

**Comment by Dumpling97** [comment]
I spent quite some time seeing if the time issue was with me, so I'll have to finish the rest tomorrow.

**Comment by Dumpling97** [comment]
Refreshing the running containers works for me with 50f8d5c now.
Will finish up with the images very soon as well
