### ISSUE TITLE
Evaluate upload runs directly

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#282]
Right now, upload runs have to be evaluated manually (by clicking on the 'evaluate' button).

Since we have the tech:
- If there is a docker-based evaluator registered, run it automatically on uploaded runs.

**Comment by mam10eks** [comment]
This is already implemented, if a Docker-based evaluator is registered for the dataset, it automatically evaluates this.
I will shortly test this and then I think we can close the issue.

**Comment by mam10eks** [comment]
I was in the train before so I was not sure if something was wrong with my connection, but now with a stable connection, the run upload is not working as well.

@MattiWe is it possible that the run upload is currently broken?

**Comment by MattiWe** [comment]
> @MattiWe is it possible that the run upload is currently broken on the client side?

Indeed, Bastian's last update broke the upload in the frontend (fixed by b67e9b2da5f1fc8f53c275bf43c43a5cc10a7e44).

**Comment by mam10eks** [comment]
Alright, I just double-checked this, and the runs are now automatically evaluated.
