### ISSUE TITLE
Allow to add and edit Metadata of Software

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#286]
It would be very nice if we could add a description for the software that we can change later.

Additionally, we should probably add the possibility to link one or multiple papers, maybe via a link to dblp entries?

This way, TIRA could link back to the ACL Anthology or also to the IR Anthology.

**Comment by mam10eks** [comment]
- Renaming Software
- Free-Form field to add a deep link to DBLP, e.g.: https://dblp.org/rec/conf/naacl/SanthanamKSPZ22.html
- Free-Form field to add a description with markdown support (use  a markdown to HTML renderer). People can write whatever they want, like "if you like this, please cite x and y")
-

**Comment by mam10eks** [comment]
Thanks @theelstner for the work.

I made a small change and placed this "Edit Software Metadata" Formular behind a "Edit-Button" toggle, so that the actual change in the frontend is rather minimal.

It works in the local deployment (i.e., without disraptor/discourse), but not in the deployed version.
Can you maybe look into the logs what is the problem? And/or test if it works in your local setup?

We do not need to fix this too urgently, as the form is hidden behind the toggle.

But as soon as it is working in the live version, I would imagine the following "final test":

- Start on https://www.tira.io/task/ir-convention-test/user/test-1-on-17-2022
- Look if you can see some Evaluation and Run outputs
- Rename the software and edit the metadata, reload the page
- Can you still see the runs? Are the Evaluation and run outputs still visible?
- Run the software
- Is the new Software execution still added to the frontend?
- Rename the software
- Run the software again
- Are during all the renamings etc. the Evaluations/runs still visible? can you change the name of the software back to the original?

**Comment by mam10eks** [comment]
ToDo: insert DOI

**Comment by mam10eks** [comment]
@theelstner I now have deployed the changes that we made in the meeting today.
It now works (I only tested it in a small example), could you please test the things from above and see if this also works?
And if this works, we can close the issue.

Thanks!

**Comment by theelstner** [comment]
I have tested it like mentioned in the comment above. Everything works, except for a minor bug (#345 Docker software runs don't show unless page is reloaded).  The bug is noted in a separate issue.
