### ISSUE TITLE
Pipeline/Multi-Step-Jobs in TIRA

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#334]
This issue aims at implementing "Multi-Step-Jobs" (or a "pipeline job", or a "chain of jobs", etc. what would be the best name?) for Docker Submissions as an analogon to VM Jobs that could use a run as input.

# User Stories

The issue addresses the following User Stories

- As a participant in an IR task, I want to run the typical two-stage jobs of first building an index of the corpus and then running an retrieval approach on the generated index, so that I save time when executing many retrieval approaches on the same index.

- As a participant in a shared task, I want that my software submission can use manually uploaded data as input, so that I can submit manual runs (e.g., manually reformulated queries in IR tasks).

# Implementation Sketch

I would like to have an implementation quite soon, so that many two-step retrieval pipelines can run over the holidays in the cluster.

Therefore, I imagine the following "version 0" that makes use of our already implemented execution of jobs:

- Users can select the previous stage of their job (might be a manually uploaded run or some other docker submission) via a select box.
- If users run a job that has a previous stage, the backend checks if the previous stage was already executed on the selected dataset:
  - The backend answers "Your Job has XXX as previous stage, but XXX was not executed on the dataset YYY, so your job can not start. Please run XXX on dataset YYY" if the previous stage was not successfully executed on the dataset.
  - The job is executed as always if the previous stage was already executed on the selected dataset. The output of the previous stage is an additional input to the job. If multiple executions of the previous stage on the selected dataset exist, it uses the newest execution as additional input to the job.

A subsequent ticket can aim at making this version 0 more user-friendly, e.g., by automatically running all jobs (only if necessary) in a pipeline.

**Comment by mam10eks** [comment]
I think I would now also favor such multi-step jobs for all re-ranking approaches in information retrieval experiments.

My line of thinking is the following:

- For each IR benchmark, we add two datasets in TIRA:
  - Full-Rank: software has access to the complete corpus
  - Re-Rank: a "pseudo dataset" where a software has access to to-be-re-ranked query document pairs

For the re-ranking scenario, one must further select which run one wants to re-rank (out of all own and public runs).
If there is an official re-ranking run (e.g., for MS MARCO), we should define them as default.
For all non-default runs, I would suggest the following:

- Users might select (some) public run of the dataset as the to-be-re-ranked run
- TIRA automatically wraps this run into an "ir-datasets-loader" job that is the previous stage of the job
  - I.e., if the run was never used before, the run is transformed by the "ir-datasets-loader" job into the "standard" to-be-re-ranked query document pair format
  - If the run was used before, the standard multi-step-thing described above kicks in so that the job itself is not executed again
- The job itself then uses the to-be-re-ranked query document pairs as "pseudo-input" (i.e., directly merged with the original input)

This has the advantage, that we can provide a set "default" runs to be re-ranked with appropriate documentation (e.g., BM25, the judgment pool with corresponding warnings that this usually tends to overestimate the effectiveness, etc) but also all other runs (and even very costly runs, as mono/duoT5 etc.) can be used directly without adoption. I think this way, we provide a big benefit, because users can even built upon very costly systems in a fast and cost-efficient way.

**Comment by heinrichreimer** [comment]
That's a really cool and very flexible way of extending TIRA :+1: 
I have two questions on how this could work:
1. This would only work with TIRA submissions which produce a standard TREC-style run file, right?
Would the run files be auto-detected in some way or do we have to specify the inputs to the ir-datasets-loader explicitly?
I would prefer the latter but that might add a bit more "friction" for users.
2. How can TIRA ensure that we don't accidentally leak private test data?
I'd guess that we cannot select _any_ previous run as the first stage but maybe rather a set of "approved" or "published" runs?
That is, a task organizer must then check the outputs of a run before they make that run available for others to re-rank.
(Thinking about a run that accidentally dumps the whole input dataset into the output directory.)
Or will the outputs of intermediate steps never be visible to participants?

**Comment by mam10eks** [comment]
Thanks @heinrichreimer for the feedback!


For the first point: I would prefer when they are "auto-detected", so that users have no effort. Although, If this would get successful and there are many runs, this would get messy, but I think we can adapt the UI in that case or switch back to "manual moderation".

To the second point: The to-be-re-ranked run would still be a normal input in TIRA. I.e., it would only be available to users if it is explicitly unblinded/published or if it is on a training/validation dataset. Otherwise, the users software can still run on confidential runs as TIRA sandoxes the software execution.

**Comment by heinrichreimer** [comment]
Nice, especially the second part :+1:  Great that this is supported out-of-the-box by the TIRA framework!
For the detection, maybe we can opt for a semi-automatic approach where TIRA "suggests" to add this step with that inputs.
Users could then change the inputs to their liking.

**Comment by mam10eks** [comment]
Yes, I think too that TIRA should only show this to users that "opt-in" to make a re-ranking submission.

**Comment by mam10eks** [comment]
This is now implemented.

Follow-up issues to make it usable:
- https://github.com/tira-io/tira/issues/356
- https://github.com/tira-io/tira/issues/357
- https://github.com/tira-io/tira/issues/358
