### ISSUE TITLE
Disraptor: Update Documentation/Schema/Conventions/Standards

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#34]
- [ ] Update the documentation to the new disraptor frontend: e.g. create a new admin/reviewer user.
- [ ] Standards/Schema regarding groups names etc: https://docs.google.com/document/d/1Jh0tyEOpHou1YiN3P1JLOVCmqPOjY-f17_PHJI_CSn8/edit?usp=sharing
- [ ] Recipies for Debugging/etc. of vms in the new dockerized host

**Comment by MattiWe** [comment]
I find this issue not specific enough. 
Disraptor docs should be in the disraptor repo. 
Webis/webis-tira conventions should be in the KB. 
Debugging guidelines should be created on the fly. Ask in DC if in doubt.
