### ISSUE TITLE
Evaluation no longer working on run upload

### ISSUE THREAD

**Issue by johanneskiesel** [tira-io/tira#359]
**Current behavior**

The evaluator is no longer (since today)  automatically run on run upload.

![image](https://user-images.githubusercontent.com/187193/210766225-0851cc00-1062-4369-9ab5-f3d2dd4c6980.png)

(valueeval-at-semeval-2023-human-value-detection; user touche23-adam-smith, dataset arguments-validation-20221205-training)

When I click on EVALUATE I get

![image](https://user-images.githubusercontent.com/187193/210766427-71af9882-b595-413f-81ef-51b71502e0fb.png)

**Expected behavior**

Evaluation should be run automatically on run upload

**Comment by mam10eks** [comment]
I have a look

**Comment by johanneskiesel** [comment]
The participant confirmed that the fix works. Thanks a lot @mam10eks !
