### ISSUE TITLE
Create CI/CD Templates for Participants

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#430]
(Idea by @hscells)

We should create github actions/ gitlab pipelines that automatically build and test docker images of participants in a shared task or teaching lab.

Main Idea:

- If we organize a shared task / teaching lab, we hand our git repositories for participants to organize their code
- This repositories already have the corresponding actions so that, for each commit, a docker build is automatically performed, and the resulting docker image is automatically uploaded to TIRA

This way, participants do not need to learn Docker, and a connection from the code to the resulting image is maintained.

What do you think? (cc @fschlatt, @MattiWe, @potthast, @kaaage)

**Comment by fschlatt** [comment]
Sounds fantastic. In my eyes, docker is at the moment the biggest barrier of entry for Tira. A concern that immediately comes to mind, if the image is built and pushed for each commit, students or participants less familiar may commit "broken" submissions quite often and it may clutter the submission system. Perhaps it should just be possible to manually execute the action for the current commit.

**Comment by mam10eks** [comment]
Super cool, @gate-tec volunteered and would be very interested to implement this.

I can be an early tester with the IR course in Jena.

We discussed a bit, and the template should make a smoke test on a very small public validation data using `tira-run` to ensure that only working images are submitted to tira.

**Comment by mam10eks** [comment]
This is implemented in the commits above
