### ISSUE TITLE
Unable to submit new run as admin

### ISSUE THREAD

**Issue by fschlatt** [tira-io/tira#462]
**Current behavior**

Using the new layout, when I click the submit button (e.g. for https://www.tira.io/task-overview/nlpfsu-summer-term-2023/causal-relation-extraction-20230613-training) the log in window pops up and I get redirected to the start page, even though I am already logged in.

**Expected behavior**

On hitting the submit button, the submission page should open.

**Comment by mam10eks** [comment]
Tested this, the commit  above resolved the issue.
