### ISSUE TITLE
Refactor Discourse specific code into dedicated Disraptor Library to simplify multiple disraptor deployments

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#480]

**Comment by mam10eks** [comment]
This is now implemented in the commit above and deployed.

**Comment by potthast** [comment]
Not sure how Disraptor-specific code in TIRA affects Disraptor?

**Comment by mam10eks** [comment]
We had discourse/disraptor specific code in TIRA that I did not want to duplicate when we have multiple apps behind disraptor, so I extracted this code to disraptor and TIRA now only uses a small disraptor dependency, and future apps also can directly use this disraptor dependencies which simplifies it to create a new app behind disraptor (e.g., ChatNoir Chat).

Examples of methods that I have extracted from TIRA and moved to disraptor are:
- Check that disraptor-specific headers are set in a request (e.g., an Disraptor secret key to verify that a request is from disraptor)
- Parsing of disraptor requests (e.g., groups, users) and subsequent checks
- Create a discourse group
- Add a discourse user to a discourse group
- Write a mail to a discourse user
- Create an Discourse API key for a user

**Comment by potthast** [comment]
Awesome, thanks!

I was often also thinking the reverse way: What would a TIRA plugin for Discourse (as part of Disraptor) look like?
