### ISSUE TITLE
Easy browsing/searching of all public components, like in aitools.

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#522]

**Comment by mam10eks** [comment]
I prepared a click dummy:

![Screenshot_20231029_094300](https://github.com/tira-io/tira/assets/10050886/e74eb184-c305-46ee-adcd-156506f844fa)

**Comment by mam10eks** [comment]
First feedback: Everything should be more dense.

**Comment by mam10eks** [comment]
The click dummy is now already in a quite good shape.

Things that I still would like to have:

- Automatic updates/deep links to the filter criteria, e.g., by updating the URL like `?focus=Recall&type=tutorial&search=query`

**Comment by Kavlahkaff** [comment]
- After filtering list should remove empty entries
- filtering should should always display parent element when searching for sub-element and when not expanded should still show sub element when searching for it

**Comment by Kavlahkaff** [comment]
- there should be a dialog opening with copyable code, for each component
