### ISSUE TITLE
Type errors when compiling, most likely due to Vuetify version change

### ISSUE THREAD

**Issue by Kavlahkaff** [tira-io/tira#593]
**Current behavior**
Code does not compile

**Expected behavior**
Code does not compile, three files seem to be broken:
<img width="1372" alt="image" src="https://github.com/tira-io/tira/assets/73996300/ba70496a-e5b0-4cad-a919-4aabf6fdde8e">

**Comment by TheMrSheldon** [comment]
Seems to be fixed since the code compiles again.
