### ISSUE TITLE
VM-Configure Fails

### ISSUE THREAD

**Issue by cakiki** [tira-io/tira#61]
**Current behavior**

VM-Configure Fails and as a result, the vm can not be accessed. Problem is that the tira id that is created is not in sync with the vboxnet ids of VBoxManage, but it is a conventeion that they must be equal.

    
**Steps to reproduce on a host**
cd tira-configure-vm
python2
 import importlib
importlib.import_module('tira-configure-vm').assign_id()

must be identical to

VBoxManage hostonlyif create

**Cause of the error**
Possible causes:
    - the long vm-name on betaweb111
    - Maybe archvie does not delete the vboxnet interface?

**Comment by MattiWe** [comment]
Please create a new issue if the problem persists.
