### ISSUE TITLE
vm-delete Does not delete vboxnet interfaces

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#62]
**Current behavior**
When I create a vm, then delete the VM, the associated vboxnet interface that is associated with the VM is not deleted

**Expected behavior**
the vboxnet should be deleted as well, this is related to the issue here: https://github.com/tira-io/tira/issues/61

**Comment by TheMrSheldon** [comment]
This issue is no longer relevant since we removed VM support.
