### ISSUE TITLE
Documentation and Setup-Notes Revisited

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#71]
Please check if setup, development, and deployment is up to date, uniform, and completely documented. We'll check the boxes in the Meetings. 
- [ ] wiki home page 
- [ ] tira-host local dev
- [ ] tira-host test deploy 
- [ ] tira-host live deploy 
- [x] tira-application local dev
- [x] tira-application test deploy 
- [x] tira-application live deploy 
- [ ] disraptor local dev
- [x] disraptor test deploy 
- [x] disraptor live deploy 
- [ ] tira-protocol local dev
- [ ] tira-protocol test deploy 
- [ ] tira-protocol live deploy 
- [ ] create VM images is stale

Documentation Example: 

## How to develop tira-application:

0. [Check out git:tira-io/tira]
1. Update the config in tira-application/config/
2. [compile protobuf]

### development setup
2. make setup
3. create a tira user. 
4. give tira user permission rw permissions on tira-model 
3. make run-dev or run-wsgi

### test deployment
2. docker-build-tira-application
3. docker-run-tira-application

### live deployment
2. docker-publish-tira-appplication
3. k8s-deploy-tira-application

### partial local dev deployment
1. E.g. local tira-application+discourse and production tira-hosts

**Comment by theelstner** [comment]
I have added a new page in the wiki with hopefully easy instructions on how to set up tira locally for development:
https://github.com/tira-io/tira/wiki/Getting-Started-as-a-TIRA-Developer

To make this as easy as possible, I have left out everything that I did not do (e.g. nearly all optional things). This is the reason for it to be a separate page for now, while the old "Host" and "application" wiki pages still remain. We have to see if we want to integrate these optional points or leave them out for the sake of simplicity.

The instructions are still to be tested on a clean ubuntu!
