### ISSUE TITLE
Show the state of the VM on the "access instruction page" of discourse.

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#74]
From a participant mail:

```
Dear committee, thank you for postponing the deadline, it looks sufficient for me.
But I still can't access Tira (I've registered this year and have confirmed the account) and try to access using instruction from https://www.tira.io/g/tira_vm_katana21
```

The VM was not running, and I believe we would improve the usability when we add the VM state on this "access instruction page" as well. (could be something very simplistic, an Iframe, etc)

**Comment by MattiWe** [comment]
@mam10eks Please check if this is still required. 
If it is, i don't understand it :)
