### ISSUE TITLE
Gibberish appended to .conf file

### ISSUE THREAD

**Issue by cakiki** [tira-io/tira#85]
**Current behavior**
Odd numbers currently appended to the supervisor log .conf files
![](https://user-images.githubusercontent.com/3664563/119015775-87897700-b999-11eb-98ee-7968f86f0704.png)

**Comment by cakiki** [comment]
@tira-io/tira-dev Can someone tell me what process writes these files?

**Comment by theelstner** [comment]
To me, it looks like it is this one: https://github.com/tira-io/tira/blob/abff435501394fd265bcc8133a443b8a4eee9d8f/tira-web/src-java/de/webis/tira/client/web/CommandLineExecutor.java#L93

**Comment by cakiki** [comment]
Thank you! Closing as the old frontend will soon be retired.
