### ISSUE TITLE
Update review page

### ISSUE THREAD

**Issue by MattiWe** [tira-io/tira#91]
- [x] limit output size of stdout
- [x] download run directory for admins (dataset page)
- [x] download output directory for users after unblinding (review page)
- [ ] show log output for admins, see #97

**Comment by BastianGrahm** [comment]
The buttons are not having any horizontal margins.
![image](https://user-images.githubusercontent.com/29681076/131650188-49b1d239-ef0b-468b-9a8e-aa6bf8ef87a5.png)
As can be seen here the button just doesn't fill up the div(?)

**Comment by MattiWe** [comment]
Siehe hier:
https://github.com/tira-io/tira/commit/306a748c6bef184748e75a310ca38a2fb414dc9f#diff-628b9883789f4177c69d5a0051e3c2855dc89b986ea46ebbd4dfe8c56e653281L74-R102

Diese UIkit Grids funktionieren auf Ebenen wie ein Gitter. Ein uk-child-width gibt den direkten Kindern diese Breite. Die Kinder der Kinder haben dann wieder ihre standard Breite. Was du vorher hattest hat den direkten Kindern (den divs) die Breite 'expand' gegeben. Die Kinder der div's (die Buttons) hatten dann ihre Standard-Breite (collapse) und waren left-aligned. 
Ich habe jetzt die divs auf 1-2 gesetzt und die Kinder der divs auf expand.

**Comment by BastianGrahm** [comment]
Vielen Dank! Auch für die Erklärung.

**Comment by mam10eks** [comment]
@BastianGrahm Is it possible that the review page is currently not working?

I just tried to update the review of a run, but my changes seem to be not persistent.

E.g., for [this run](https://www.tira.io/task/touche-task-2/user/princess-knight/dataset/touche-2022-task2/run/2022-01-18-10-06-21) I have written a review but when I click on the "Submit Review" button nothing changes, and after reloading the page my review is gone.
