### ISSUE TITLE
vboxmanage block and inconsistent prometheus checks

### ISSUE THREAD

**Issue by mam10eks** [tira-io/tira#95]
I move this issue from the webis-admin issues to the TIRA issues.

The content of the issue:

Infrequently, vboxmanage hangs and does not return. This also blocks all subsequent calls to vboxmanage, resulting in large numbers of zombie processes. Restarting vboxdrv via systemd does not resolve these calls. Why exactly this happens is unclear. Apparently, only the tira user is affected. Vboxmanage works for the webis user while being blocked for the tira user.

Affected machines:
- tira user on various betaweb machines

Steps to reproduce:
- unclear

Steps to solve:
- Killing the process VBoxXPCOMIPCD resolved these blocked calls on betaweb043.

Open issues:
- [ ] There was no Prometheus warning of the issue, there should be one.  
- [ ] Reproduce the issue/find source
- [ ] Check if the solution is actually correct or was just coincidental

**Comment by MattiWe** [comment]
I'll close this, as it is webis specific and should be in the webis-gitlab. Please assign tira devs there.
